[package]
name = "rust_gnuplot"
version = "0.1.0"
authors = ["Hg <86350771+malibu-cola@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gnuplot = "0.0.24"